"""add_is_archived_to_articles

Revision ID: 9dea4a8d09de
Revises: 0a3cc3fd6192
Create Date: 2026-05-22 19:10:07.116869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dea4a8d09de'
down_revision: Union[str, None] = '0a3cc3fd6192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('articles', sa.Column('is_archived', sa.Integer(), nullable=True))
    # Set existing rows to 0 (active)
    op.execute("UPDATE articles SET is_archived = 0 WHERE is_archived IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_archived')
    # ### end Alembic commands ###
